version: '3.8'

services:
  app:
    build: .
    container_name: cloud_etl_app
    volumes:
      - .:/usr/src/app
      - ./api-log:/usr/src/app/api-log
      - ./json-base:/usr/src/app/json-base
    command: python run.py
